### PR TITLE
Fix the view-model editor height cut off

### LINKED ISSUE #86: Editor: VM get's cut off
Within the editor the ViewModel representation is being cut short:

Screenshot 2019-04-11 at 22 26 24

### PR DESCRIPTION
**Pull request by cherifGsoul**
Fixes #86 

The logic behind the fix is to calculate the height of the view-model editor in two cases:

_**1. When the breakpoints section is expanded**_: The real/actual occupied height (not the max-height) by the breakpoints editor is be added to the view-model height in order to keep it visible in the two thirds of the available height space.

_**2. When the breakpoints section is not expanded**_: Here the view-model editor will have the height of the available space but without the height of breakpoints section in order to prevent scrolling outside the view-model editor.

I added properties to bound `expanded-section` component height and the height of the collapsible title with `components-panel` component.

### CODE REVIEW

File: expandable-section/expandable-section.js [hunk 1]
```diff
@@ -11,6 +11,37 @@ export default Component.extend({
...
+		sectionTitle: {
+			type: "any"
+		},
+		/**
+		 * the actual section height (height property is for max-height)
+		 */
+		sectionHeight: {
+			value({lastSet, listenTo, resolve}) {
+				resolve(lastSet.get());
+				listenTo("sectionEl", (ev, el) => {
```
Comment (phillipskevin) [inline expandable-section/expandable-section.js]: Could this just be a getter? Also, can you write tests for these?

Comment (cherifGsoul) [reply expandable-section/expandable-section.js]: I wrote tests and getters.

I'm not able to reproduce the double scrollbar, when you are online, can you give me more details to reproduce it?

**Comment by phillipskevin** [comment]
I found another weird case that we should try to fix. The steps to reproduce are

1. scroll the ViewModel Editor all the way to the bottom
2. click in the empty space so the ViewModel Editor will add a new property to the end
3. Type anything, hit `tab`, type anything, hit `enter`
4. Scroll to the top
5. Notice the breakpoints panel is off the screen

Here's a gif:
vm-resize-bug

Let me know if you have trouble reproducing it, @cherifGsoul.

File: panel/panel.js [hunk 2]
```diff
@@ -13,24 +13,29 @@ export default Component.extend({
...
+				this.viewModelTitleHeight = this.viewModelTitle.clientHeight;
 			};
 
 			// set default height
 			setHeight();
 
 			// set height when page is resized
 			window.addEventListener("resize", setHeight);
-
+
```
Comment (phillipskevin) [inline panel/panel.js]: can you remove this space?

File: panel/panel.js [hunk 3]
```diff
@@ -50,11 +55,19 @@ export default Component.extend({
 		breakpoints: DefineList,
 		breakpointsError: "string",
 
+		//breakpoints DOM fields
+		breakpointsExpanded: "boolean",
```
Comment (phillipskevin) [inline panel/panel.js]: Should this be under `breakpoints fields` since it's not really DOM related.

File: panel/panel.js [hunk 4]
```diff
@@ -89,18 +102,25 @@ export default Component.extend({
...
-						addBreakpoint:from="addBreakpoint"
-						toggleBreakpoint:from="toggleBreakpoint"
-						deleteBreakpoint:from="deleteBreakpoint"
-						error:bind="breakpointsError"
-					></breakpoints-editor>
-				</expandable-section>
+			<div class="sidebar" style="height: {{scrollableAreaHeight}}px">
+					
+					<expandable-section title:raw="ViewModel Mutation Breakpoints" sectionTitle:to="breakpointsTitle" height:from="breakpointsHeight"
+										expanded:bind="breakpointsExpanded"
```
Comment (phillipskevin) [inline panel/panel.js]: can you fix this indentation?

File: panel/panel.js [hunk 5]
```diff
@@ -89,18 +102,25 @@ export default Component.extend({
...
+							deleteBreakpoint:from="deleteBreakpoint"
+							error:bind="breakpointsError"
+						></breakpoints-editor>
+					</expandable-section>
+					
 
-				<expandable-section title:raw="ViewModel Editor" expanded:from="true" height:bind="viewModelEditorHeight">
+					
+					<expandable-section title:raw="ViewModel Editor" expanded:from="true" sectionTitle:to="viewModelTitle"
+										height:from="viewModelEditorHeight"
```
Comment (phillipskevin) [inline panel/panel.js]: can you fix this indentation also?

File: panel/panel.js [hunk 6]
```diff
@@ -111,7 +131,9 @@ export default Component.extend({
 						expandedKeys:to="expandedKeys"
 						error:bind="viewModelEditorError"
 					></viewmodel-editor>
-				</expandable-section>
+						
+					</expandable-section>
```
Comment (phillipskevin) [inline panel/panel.js]: Is this indented correctly? It's hard to tell from the diff.
